# -*- coding: utf-8 -*-
"""main_ibm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ar9W7lHbAGxI2RJjQQ3u0zRwIqj-GVsV
"""

# ⬆️ Upload the CSV file
from google.colab import files
import pandas as pd

uploaded = files.upload()   # Upload 'feedback.csv'

# 📊 Load the CSV file into a DataFrame
feedback_data = pd.read_csv("feedback.csv")

# 🔍 Print first few rows
print("✅ Snippet 1 Output - First 5 Feedback Entries:")
print(feedback_data.head())

import pandas as pd
feedback_data = pd.read_csv("feedback.csv")

# 📝 Improved classifier based on keywords
def classify_with_flanst(feedback_text):
    feedback_lower = feedback_text.lower()

    academics_keywords = [
        "teacher", "syllabus", "assignment", "exam", "lecture", "faculty", "curriculum",
        "subject", "classes", "teaching"
    ]

    facilities_keywords = [
        "wifi", "projector", "hostel", "canteen", "equipment", "library", "gym", "chair",
        "air conditioning", "lab", "bus", "toilet", "water"
    ]

    admin_keywords = [
        "admin", "office", "form", "certificate", "transcript", "application", "placement",
        "fee", "document", "admission", "clearance", "registration"
    ]

    if any(k in feedback_lower for k in academics_keywords):
        return "Academics"
    elif any(k in feedback_lower for k in facilities_keywords):
        return "Facilities"
    elif any(k in feedback_lower for k in admin_keywords):
        return "Administration"
    else:
        return "Unknown"

# 🪄 Apply classifier to each feedback entry
feedback_data["Predicted_Category"] = feedback_data["Feedback"].apply(classify_with_flanst)

# 🔍 Show a preview
print("✅ Snippet 3 Output - First 10 Rows with Predictions:")
print(feedback_data.head(10))

# 💾 Save to new CSV
final_filename = "final_college_feedback_classified.csv"
feedback_data.to_csv(final_filename, index=False)

# ⬇️ Download file
files.download(final_filename)

print(f"✅ Snippet 4 Output - File '{final_filename}' saved and ready for download.")